python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-probe_b10.pkl Sub_probe_before10
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-probe_b20.pkl Sub_probe_before20
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-probe_b30.pkl Sub_probe_before30
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-probe_b40.pkl Sub_probe_before40
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-probe_bTrial.pkl Sub_probe_beforeTrial
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-response_b10.pkl Sub_response_before10
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-response_b20.pkl Sub_response_before20
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-response_a10.pkl Sub_response_after10
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-sub_D-response_a20.pkl Sub_response_after20
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-obj_D-response_b10.pkl Obj_response_before10
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-obj_D-response_b20.pkl Obj_response_before20
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-obj_D-response_a10.pkl Obj_response_after10
python3 src/preprocess/gsr_extraction.py ./data/seg_data/L-obj_D-response_a20.pkl Obj_response_after20