python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_probe_before10.csv Sub_probe_before10
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_probe_before20.csv Sub_probe_before20
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_probe_before30.csv Sub_probe_before30
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_probe_before40.csv Sub_probe_before40
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_probe_beforeTrial.csv Sub_probe_beforeTrial
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_response_before10.csv Sub_response_before10
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_response_before20.csv Sub_response_before20
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_response_after10.csv Sub_response_after10
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Sub_response_after20.csv Sub_response_after20
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Obj_response_before10.csv Obj_response_before10
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Obj_response_before20.csv Obj_response_before20
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Obj_response_after10.csv Obj_response_after10
python3 src/train/trainGSR_xgb_binary.py ./data/feature_data/Obj_response_after20.csv Obj_response_after20